
development:
  adapter: postgresql
  encoding: unicode
  database: thegothic_development
  pool: 5
  prepared_statements: false

test:
  adapter: postgresql
  encoding: unicode
  database: thegothic_test
  pool: 5



